default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>

development:
  <<: *default
  database: kiroku_development

test:
  <<: *default
  database: kiroku_test

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV["POSTGRES_DB"] %>
    username: <%= ENV["POSTGRES_USER"] %>
    password: <%= ENV["POSTGRES_PASSWORD"] %>
    host: <%= ENV["DB_HOST"] %>
    port: <%= ENV["DB_PORT"] %>
  cache:
    <<: *primary_production
    database: kiroku_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: kiroku_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: kiroku_cable
    migrations_paths: db/cable_migrate
